#!/bin/bash
setxkbmap -option caps:escape &
numlockx &

feh --bg-fill /home/joel/dotfiles/wallpaper.png &
tint2 &
(sleep 2 && conky) &

redshift -l 51.0486:-114.0708 &
xscreensaver -no-splash &
thunar --daemon &
volti &
